Update Agate-sql to version 0.5.8
AnacondaRecipes/agate-sql-feedstock pull request #3
Opened 2021-10-19 14:41 UTC by varlackc

1. check the upstream
https://github.com/wireservice/agate-sql/tree/0.5.8

2. check the pinnings
https://github.com/wireservice/agate-sql/blob/0.5.8/setup.py
https://github.com/wireservice/agate-sql/blob/0.5.8/setup.cfg
https://github.com/wireservice/agate-sql/blob/0.5.8/example.py

corrected the python pinings

3. check changelogs
https://github.com/wireservice/agate-sql/blob/0.5.8/CHANGELOG.rst

There were only bug fixes mentioned in the change log, for example:
- Fix tests for Linux packages.

4. additional research
https://github.com/conda-forge/agate-sql-feedstock/issues

There are currently no open issues in conda-forge

5. verify dev_url
6. verify doc_url
7. added pip to the test section
8. verify the test section
9. additional tests

In order to test the `agate-sql` package version `0.5.8` the following test was conducted
`conda build agate-sql-feedstock --test`
The test result was the following:
`All tests passed`

In additioon to test the `scvkit` package was used to test `agate` 
`conda build csvkit-feedstock --test`
the test result was the following:
`All tests passed`

Based on the research finding and on the test results we can conclude that it is safe to update `agate-sql` to version `0.5.8`

2021-10-21 14:21 UTC, skupr-anaconda commented
Please add missing packages `pip` and `wheel` to the host section.
And why `pip check` is disabled?

2021-10-21 16:05 UTC, varlackc commented
> Please add missing packages `pip` and `wheel` to the host section. And why `pip check` is disabled?

`Pip` and `wheel` were added to the host section
https://github.com/AnacondaRecipes/agate-sql-feedstock/blob/update_to_0.5.8/recipe/meta.yaml#L26&L27

In addition the `pip check` was added to the test section.
https://github.com/AnacondaRecipes/agate-sql-feedstock/blob/update_to_0.5.8/recipe/meta.yaml#L36&L41

2021-10-22 08:43 UTC, skupr-anaconda commented
We should build pyicu first then build agate 1.6.2 or a new 1.6.3

2021-10-22 09:04 UTC, katietz reviewed
Is the agate dependency correct?

2021-10-22 10:54 UTC, skupr-anaconda commented
I'm building `pyicu 2.7.4` for `agate 1.6.3` https://github.com/AnacondaRecipes/pyicu-feedstock/pull/1

2021-11-03 10:56 UTC, katietz requested changes

2021-11-03 10:56 UTC, katietz commented on recipe/meta.yaml
> +  skip: true  # [s390x]
Why we skip on s390x?  It is a dependency, I guess.  So please give here a comment

2021-11-03 14:00 UTC, varlackc commented on recipe/meta.yaml
>    noarch: python
Specify the missing dependencies `parsedatetime` and `agate ` in s390x

2021-11-04 11:38 UTC, skupr-anaconda approved these changes

2021-11-05 14:25 UTC, katietz approved these changes
thanks

2021-12-08 11:54 UTC, skupr-anaconda commented
@varlackc Should we merge or close this PR?

2021-12-10 20:13 UTC, merged